# Generated by Django 3.0.14 on 2022-02-24 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220224_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_field',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
